config/routes.rb
Rails.application.routes.draw do

  get 'passwords/new'

  get 'passwords/edit'

  root 'main#index'

  resources :users

  resources :students
  
  resources :reviews

  resources :cohorts

  resources :deliverables

  get 'login', to: 'sessions#new'

  post 'login', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  get 'reset' => 'passwords#new'

  post 'reset' => 'passwords#create'

  get 'reset/:code' => 'passwords#edit', as: :reset_code

  put 'reset/:code' => 'passwords#update'

end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :user
  has_many :reviews
  has_many :deliverables, through: :cohort
  has_and_belongs_to_many :cohorts, through: :cohorts_students, inverse_of: :student

  accepts_nested_attributes_for :reviews
  accepts_nested_attributes_for :cohorts
  accepts_nested_attributes_for :user

  validates :brand,
    allow_nil: true,
    allow_blank: true,
    length: {in: 10..600}

  validates :linkedin,
    allow_nil: true,
    allow_blank: true,
    :url => true

  validates :resume,
    allow_nil: true,
    allow_blank: true,
    :url => true

  validates :jobtracker,
    allow_nil: true,
    allow_blank: true,
    :url => true

  validates :portfolio,
    allow_nil: true,
    allow_blank: true,
    :url => true

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  before_action :is_authenticated
  before_action :is_admin, only: [:index]
  
  before_action :is_student, only: [:edit, :update]


  def index
    @users = User.all
    @cohorts = Cohort.all

    if (params[:cohort] && params[:cohort][:cohort] && params[:cohort][:cohort] != '')
      @students = User.joins(:student, :cohorts).select('*').where(cohorts:{cohort: params[:cohort][:cohort]})
      @deliverables = Deliverable.select('deliverables.id AS deliverable_id, *').joins(:cohort).where(cohorts:{cohort: params[:cohort][:cohort]})
    else
      @students = User.joins(:student, :cohorts).select('*')
      @deliverables = Deliverable.joins(:cohort).select('deliverables.id AS deliverable_id, *')
    end
  end

  def show
    @user = User.find(params[:id])
    person = @user.student.id
    @review = Review.where(student_id: person)
    @brand = []
    @linkedin = []
    @resume = []
    @jobtracker = []
    @portfolio = []
    @review.each do |review|
      if review.review_type == 'brand'
        @brand.push(review)
      elsif review.review_type == 'linkedin'
        @linkedin.push(review)
      elsif review.review_type == 'resume'
        @resume.push(review)
      elsif review.review_type == 'jobtracker'
        @jobtracker.push(review)
      elsif review.review_type == 'portfolio'
        @portfolio.push(review)
      end
    end
  end

  def edit
    @student = Student.find(params[:id])
  end

  def create
    @picks = Staffpick.create(staff_params)
    redirect_to root_path
  end

  def update
    if @current_user
      student = Student.find(params[:id])
      student.update(student_params)
      redirect_to student_path(student.user_id)
    end
  end

  private
  
  def student_params
     params.require(:student).permit(:brand, :linkedin, :resume, :jobtracker, :portfolio, :user_id => [])
  end

  def staff_params
    params.require(:picks).permit(:name, :url, :staff_attending, :host_location, :notes, :date)
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_students_cohorts.html.erb
<!-- Secondary Nav tabs -->
<div>

  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#home2" aria-controls="home2" role="tab" data-toggle="tab">Cohort List</a></li>
    <li role="presentaion"><a href="#deliverables" aria-controls="deliverables" role="tab" data-toggle="tab">Deliverables</a></li>
  </ul>

<!-- Tab panes -->
<div class="tab-content">

  <!-- Students tab -->
  <div role="tabpanel" class="tab-pane active" id="home2">

    <h3>Students</h3>

    <table class="table">
      <tbody>
        <% @students.each do |student| %>
          <tr>
            <td><a href="students/<%=student.user_id%>"><%= student.name %></a></td>
            <td><%= student.cohort %></td>
            <td><%= link_to('Edit User', edit_user_path(student.user_id), class: 'btn btn-default') %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div> <!-- End Students -->

  <!-- Deliverables Tab -->
  <div role="tabpanel" class="tab-pane fade" id="deliverables">
    <div>
      <h3 class="deliverable-header">Deliverables</h3>
      <h4 class="deliverable-header" "></h4>
      <div class="pull-right">
        <%= link_to('Add deliverable to cohort', new_deliverable_path, class: 'btn btn-default new-d') %>
      </div>
    </div>

    <table class="table">
      <thead><tr>
        <th>Type</th>
        <th>Name</th>
        <th>Notes</th>
        <th>Due_Date</th>
      </tr></thead>
      <tbody>
        <% @deliverables.each do |s| %>
        <tr>
          <td><%= s.deliverable_type %></td>
          <td><%= s.deliverable_name %></td>
          <td><%= s.notes %></td>
          <td><%= s.due_date.to_formatted_s(:short) %></td>
          <td><%= link_to('Edit', edit_deliverable_path(s.deliverable_id), class: 'btn btn-default') %></td>
        </tr>
      <% end %>
      </tbody>
    </table>

  </div> <!-- End Deliverables -->

  <!-- Tab -->
  <div role="tabpanel" class="tab-pane fade" id="#">
  </div>

</div>
<!-- end Tab Panes -->

</div>
<!-- end Nav Tabs -->

app/views/students/edit.html.erb
<div class="page-header">
  <h1>Edit</h1>
</div>

app/views/students/index.html.erb
<div class="page-header">
  <h1>Administrator Management Page</h1>
</div>

<!-- Nav tabs -->
<div>

  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Students</a></li>
    <li role="presentation"><a href="#admins" aria-controls="admins" role="tab" data-toggle="tab">Admins</a></li>
    <li role="presentation"><a href="#staff-picks" aria-controls="staff-picks" role="tab" data-toggle="tab" class="nav-tabs-left">Staff Picks</a></li>
    <li role="presentation"><a href="#new-user" aria-controls="new-user" role="tab" data-toggle="tab" class="nav-tabs-left">New User</a></li>
  </ul>

<!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane fade in active" id="home">
      <!-- Cohort -->
      <h3>By Cohort</h3>
      <div class=" form pull-right">
      <%= render '/cohorts/new', :locals => {:cohort => Cohort.new} %>
      </div>
      <!-- Select filter -->
      <div class="filter_options_container">
        <form class="filter_form">
            <%= select("cohort", "cohort", Cohort.all.collect(&:cohort), :include_blank => true, class: "form-control") %>     
          <input class="btn btn-default" id= "form-submit" type="submit" value="Filter" />
        </form>
        <div>
          <h3 id="cohort-display"></h3>
        </div>
      </div>
      <hr>

      <!-- Secondary Students Nav -->
      <%= render :partial => 'students_cohorts', :student => @students %>
      </div>
      <!-- end student tab-->

    <!-- Admin tab -->  
    <div role="tabpanel" class="tab-pane fade" id="admins">
      <table class="table">
        <tbody>
          <% @users.order('name ASC').each do |user| %>
            <% if user.admin %>
              <tr>
                <td><%= user.name %></td>
                <td><%= user.email %></td>
                <td><%= link_to('Edit User', edit_user_path(user.id), class: 'btn btn-default') %></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>    
    </div>

  <!-- Staff-Picks Tab -->
    <div role="tabpanel" class="tab-pane fade" id="staff-picks">
      <h3>Enter a Staff Favorite Meet Up</h3>
      <%= bootstrap_form_for(:picks) do |p| %>

        <%= p.text_field :name %>
        <%= p.text_field :url %>
        <%= p.text_field :host_location %>
        <%= p.text_field :staff_attending %>
        <%= p.text_field :notes %>
        <%= p.date_field :date %>
        <%= p.submit %>
      <% end %>
    </div>

    <!-- New User tab -->
    <div role="tabpanel" class="tab-pane fade" id="new-user">
      <h3>New User</h3>
      <!-- New User Form -->
      <%= render '/users/new' %>
    </div>

  </div>
  <!-- end Tab Panes -->
</div>
<!-- end Nav Tabs -->

app/views/students/show.html.erb
<div class="students-profile">
<!--   <div class="profile"> -->
    <div class="row">
      <div class="profile-header">
        <!-- This is the Profile Header Row -->
        <div class="prof-head-col">
          <h1><%=@user.name%></h1>
          <%@user.student.cohorts.each do |cohort|%>
            <span><%=cohort.cohort%></span>
          <% end %>
        </div>
        <div class="prof-head-col">
        <% if !@current_user.admin && @current_user == @user %>
          <button class="edit">Edit Profile</button>
          <div class="password"><%= link_to 'Change Password', edit_user_path(params[:id]) %>
          </div>
        <% end %>
        </div>
      </div>
    </div>
    <!-- This is the student's deliverables -->
    <%= form_for @user.student do |f| %>
      <!-- Branding Statement -->
      <a href="#" class="link-right">Cancel</a>
      <div class="row brand">
        <h2>Branding Statement</h2>
        <div class="branding">
          <p class="hide_on_edit"><%= @user.student.brand %>
          </p>
          <%= f.text_area :brand, class: 'update focus show_on_edit', :autofocus => true %>
        </div>
        <% if @user != @current_user %>
          <a href="#" class="comment_brand">Leave a Comment</a>
        <% elsif @user == @current_user && @brand.length > 0 %>
          <a href="#" class="reviews_brand">See Reviews</a>
          <a href="#" class="close_brand">Close</a>
        <% end %>
      </div>

      <!-- Resume -->
      <div class="row">
        <p>
          <h2>Resume Link</h2>
          <a class="hide_on_edit" href="<%= @user.student.resume %>"> <%= @user.student.resume %>
          </a>
        </p>
        <%= f.url_field :resume, class: 'url-link update show_on_edit'%>
        <% if @user != @current_user %>
          <a href="#" class="comment_resume">Leave a Comment</a>
        <% elsif @user == @current_user && @resume.length > 0 %>
          <a href="#" class="reviews_resume">See Reviews</a>
          <a href="#" class="close_resume">Close</a>
        <% end %>
      </div>

      <!-- LinkedIn Link -->
      <div class="row">
        <p>
          <h2>LinkedIn Link</h2>
          <a class="hide_on_edit" href="<%= @user.student.linkedin %>"> <%= @user.student.linkedin %>
          </a>
        </p>
        <%= f.url_field :linkedin, class: 'url-link update show_on_edit' %>
        <% if @user != @current_user %>
          <a href="#" class="comment_linkedin">Leave a Comment</a>
        <% elsif @user == @current_user && @linkedin.length > 0 %>
          <a href="#" class="reviews_linkedin">See Reviews</a>
          <a href="#" class="close_linkedin">Close</a>
        <% end %>
      </div>

      <!-- Portfolio -->
      <div class="row">
        <p><h2>Portfolio Link</h2>
          <a class="hide_on_edit" href="<%= @user.student.portfolio %>"> <%= @user.student.portfolio %>
          </a>
        </p>
        <%= f.url_field :portfolio, class: 'url-link update show_on_edit'%>
        <% if @user != @current_user %>
          <a href="#" class="comment_portfolio">Leave a Comment</a>
        <% elsif @user == @current_user && @portfolio.length > 0 %>
          <a href="#" class="reviews_portfolio">See Reviews</a>
          <a href="#" class="close_portfolio">Close</a>
        <% end %>
      </div>

      <!-- Job Tracker Link -->
      <div class="row">
        <p>
          <h2>Job Tracker</h2>
          <a class="hide_on_edit" href="<%= @user.student.jobtracker %>"> <%= @user.student.jobtracker %>
          </a>
          </p>
        <%= f.url_field :jobtracker, class: 'url-link update show_on_edit'%>
        <% if @user != @current_user %>
          <a href="#" class="comment_jobtracker">Leave a Comment</a>
        <% elsif @user == @current_user && @jobtracker.length > 0 %>
          <a href="#" class="reviews_jobtracker">See Reviews</a>
          <a href="#" class="close_jobtracker">Close</a>
        <% end %>
      </div>

      <%= f.submit class: 'submit-button'%>
    <% end %>
<!-- ^ABOVE: END OF EDIT PROFILE FORM ^ -->

<!-- END .PROFILE -->
  <!-- </div> -->


<!-- ACCORDIANS FOR SEEING COMMENTS -->
  <div class="accordion_brand">
    <% @brand.each do |brand|%>
      <h3>From: <%=brand.reviewer_name%></h3>
      <div>
        <p><%=brand.review_content%></p>
      </div>
    <% end %>
  </div>
      
  <div class="accordion_resume">
    <% @resume.each do |resume|%>
      <h3>From: <%=resume.reviewer_name%></h3>
      <div>
        <p><%=resume.review_content%></p>
      </div>
    <% end %>
  </div>

  <div class="accordion_linkedin">
    <% @linkedin.each do |linkedin|%>
      <h3>From: <%=linkedin.reviewer_name%></h3>
      <div>
        <p><%=linkedin.review_content%></p>
      </div>
    <% end %>
  </div>

  <div class="accordion_portfolio">
    <% @portfolio.each do |portfolio|%>
      <h3>From: <%=portfolio.reviewer_name%></h3>
      <div>
        <p><%=portfolio.review_content%></p>
      </div>
    <% end %>
  </div>

  <div class="accordion_jobtracker">
    <% @jobtracker.each do |jobtracker|%>
      <h3>From: <%=jobtracker.reviewer_name%></h3>
      <div>
        <p><%=jobtracker.review_content%></p>
      </div>
    <% end %>
  </div>

<!-- END OF ACCORDIANS -->

<!-- FORMS FOR ADDING A COMMENT -->
  <div class="comment_form_brand">
    <%= form_for @review = Review.new do |r| %>
      <%= r.hidden_field :student_id, :value => @user.student.id %>
      <%= r.hidden_field :review_type, :value => 'brand' %>
      <%= r.hidden_field :reviewer_name, :value => @current_user.name %>
      <%= r.text_area :review_content, class: 'feild'%>      
      <%= r.submit class:'send' %>
    <% end %>
    <a href="#" class="cancel_brand">Cancel</a>
  </div>


  <div class="comment_form_resume">
    <%= form_for @review = Review.new do |r| %>
      <%= r.hidden_field :student_id, :value => @user.student.id %>
      <%= r.hidden_field :review_type, :value => 'resume' %>
      <%= r.hidden_field :reviewer_name, :value => @current_user.name %>
      <%= r.text_area :review_content, class: 'feild' %>
      <%= r.submit class:'send' %>
    <% end %>
    <a href="#" class="cancel_resume">Cancel</a>
  </div>

  <div class="comment_form_linkedin">
    <%= form_for @review = Review.new do |r| %>
      <%= r.hidden_field :student_id, :value => @user.student.id %>
      <%= r.hidden_field :review_type, :value => 'linkedin' %>
      <%= r.hidden_field :reviewer_name, :value => @current_user.name %>
      <%= r.text_area :review_content, class: 'feild' %>
      <%= r.submit class:'send' %>
    <% end %>
    <a href="#" class="cancel_linkedin">Cancel</a>
  </div>

  <div class="comment_form_portfolio">
    <%= form_for @review = Review.new do |r| %>
      <%= r.hidden_field :student_id, :value => @user.student.id %>
      <%= r.hidden_field :review_type, :value => 'portfolio' %>
      <%= r.hidden_field :reviewer_name, :value => @current_user.name %>
      <%= r.text_area :review_content, class: 'feild' %>      
      <%= r.submit class:'send' %>
    <% end %>
    <a href="#" class="cancel_portfolio">Cancel</a>
  </div>

  <div class="comment_form_jobtracker">
    <%= form_for @review = Review.new do |r| %>
      <%= r.hidden_field :student_id, :value => @user.student.id %>
      <%= r.hidden_field :review_type, :value => 'jobtracker' %>
      <%= r.hidden_field :reviewer_name, :value => @current_user.name %>
      <%= r.text_area :review_content, class: 'feild'%>
      <%= r.submit class:'send' %>
    <% end %>
    <a href="#" class="cancel_jobtracker">Cancel</a>
  </div>
<!-- END FORMS FOR CREATING COMMENTS -->

<!-- END OF CONTAINER FOR STUDENTS SHOW PAGE .STUDENTS-PROFILE -->
</div>