config/routes.rb
Rails.application.routes.draw do

  get 'passwords/new'

  get 'passwords/edit'

  root 'main#index'

  resources :users

  resources :students
  
  resources :reviews

  resources :cohorts

  resources :deliverables

  get 'login', to: 'sessions#new'

  post 'login', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  get 'reset' => 'passwords#new'

  post 'reset' => 'passwords#create'

  get 'reset/:code' => 'passwords#edit', as: :reset_code

  put 'reset/:code' => 'passwords#update'

end

app/models/cohort.rb
class Cohort < ActiveRecord::Base
  has_and_belongs_to_many :students, through: :cohorts_students
  accepts_nested_attributes_for :students
  has_many :users, through: :students
  has_many :deliverables
  
  validates :cohort,
    uniqueness: {case_sensitive: false}
end

app/models/cohorts_students.rb
class CohortsStudents < ActiveRecord::Base
  belongs_to :cohort
  belongs_to :student
  has_one :user, through: :student
  has_many :deliverables, through: :cohort
end

app/models/deliverable.rb
class Deliverable < ActiveRecord::Base
  belongs_to :cohort, inverse_of: :deliverables
  accepts_nested_attributes_for :cohort
end

app/models/review.rb
class Review < ActiveRecord::Base
  has_one :student
  has_one :user, through: :student

  accepts_nested_attributes_for :student

  validates :review_content,
    length: { maximum: 600 }
end

app/models/staffpick.rb
class Staffpick < ActiveRecord::Base

  validates :name,
    presence: true,
    length: {in: 1..30}

  validates :url,
    presence: true,
    url: true,
    uniqueness: {case_sensitive: false}

end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :user
  has_many :reviews
  has_many :deliverables, through: :cohort
  has_and_belongs_to_many :cohorts, through: :cohorts_students, inverse_of: :student

  accepts_nested_attributes_for :reviews
  accepts_nested_attributes_for :cohorts
  accepts_nested_attributes_for :user

  validates :brand,
    allow_nil: true,
    allow_blank: true,
    length: {in: 10..600}

  validates :linkedin,
    allow_nil: true,
    allow_blank: true,
    :url => true

  validates :resume,
    allow_nil: true,
    allow_blank: true,
    :url => true

  validates :jobtracker,
    allow_nil: true,
    allow_blank: true,
    :url => true

  validates :portfolio,
    allow_nil: true,
    allow_blank: true,
    :url => true

end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :student
  has_many :cohorts, through: :student
  has_many :reviews, through: :student
  has_many :deliverables, through: :cohorts

  #attr_accessor :name, :email
  
  accepts_nested_attributes_for :student

  has_secure_password
  
  validates :name,
    presence: true,
    length: {in: 1..30}

  validates :email,
    presence: true,
    email: true,
    uniqueness: {case_sensitive: false}

  validates :password,
    length: {in: 8..72},
    on: :create


  def self.authenticate(params)
    User.find_by_email(params[:email]).try(:authenticate, params[:password])
  end

  def set_password_reset
    self.reset_code = loop do
      code = SecureRandom.urlsafe_base64
      break code unless User.exists?(reset_code: code)
    end
    self.expires_at = 4.hours.from_now
    self.save
  end
  
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def index
    zip = '98101'
    country = 'USA'
    city = 'Seattle'

    if !params[':topic'] || params[':topic'] == ''
      @topic = 'Web'
    else
      @topic = params[':topic'].gsub(/\s+/, "")
    end

    begin
      data = RestClient.get 'https://api.meetup.com/2/open_events?sign=true&photo-host=public&zip=' + zip + '&country=' + country + '&topic=' + @topic + '&city=' + city + '&state=WA&page=20&key=23145310778c71694fbb51774f'
    rescue
      flash[:danger] = 'No Search Results, please try again'
      puts 'I am rescued'
    end
     #  @data = JSON.parse(data)

    if data == nil
      flash[:danger] = 'No Search Results, please try again'
    else
      @data = JSON.parse(data)
    end

    @picks = Staffpick.all
    # @cohorts = Cohort.all
    # @users = User.all

    if (params[:cohort] && params[:cohort][:cohort] && params[:cohort][:cohort] != '')
      @students = User.joins(:student, :cohorts).select('*').where(cohorts:{cohort: params[:cohort][:cohort]})
      @deliverables = Deliverable.select('*').joins(:cohort).where(cohorts:{cohort: params[:cohort][:cohort]})
      @cohorts = Cohort.select('*').where(id: user_cohort)
    else
      @students = User.joins(:student, :cohorts).select('*')
      @deliverables = Deliverable.joins(:cohort).select('*')
      @cohorts = Cohort.all
    end

      # render json: @cohorts

    # if (@current_user.admin == false)
    #   @students = User.select('*').joins(:student, :cohorts)
    #   # .where(cohort_id: user_cohort)
    #   @deliverables = Deliverable.select('*').joins(:cohort).where(cohort_id: user_cohort)
    #   @cohorts = Cohort.select('*').where(id: user_cohort)
    # elsif @current_user.admin == true
    #   @students = User.joins(:student, :cohorts).select('*')
    #   @deliverables = Deliverable.joins(:cohort).select('*')
    #   @cohorts = Cohort.all
    # end 

  end

  private

  def user_cohort
    current_student = Student.where(user_id: @current_user.id).pluck(:id)
    expected_cohort = CohortsStudents.where(student_id: current_student).pluck(:cohort_id)
    return expected_cohort
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :is_authenticated
  before_action :is_admin, except: [:edit, :update]

  # create a new blank template for user, direct to new user page
  def new
    @user = User.new
  end

  # create a new user in the db, redirect to admin profile
  def create
    user = User.new(user_params)
    if user.save && !user.admin
      user.create_student
      CohortsStudents.create(cohort_id: params[:cohorts_students][:cohort_id], student_id: user.student.id)
      redirect_to students_path
    elsif user.save && user.admin
      redirect_to students_path
    else
      flash[:danger] = user.errors.messages
      redirect_to new_user_path
    end
  end

  # pull user info, populate form, pull up form
  def edit
    @user = User.find_by_id(params[:id])
  end

  # update already existing user
  def update
    User.find(params[:id]).update(user_params)

    person = User.find(params[:id])

    if person.student && @current_user.admin
      check = CohortsStudents.where(student_id: person.student.id).update_all(cohort_id: params[:cohorts_students][:cohort_id])
    end

    redirect_to students_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin, :cohort_ids => [])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/helpers/deliverables_helper.rb
module DeliverablesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/staffpicks_helper.rb
module StaffpicksHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ComingUp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>

  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.theme.min.css">
   
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">

</head>
<body>

  <%= render '/partials/navBar' %>

  <div class="container flash-box">
    <%= render '/partials/flash' %>
    <%= yield %>
  </div>
<!-- <script src="https://code.jquery.com/jquery-1.12.4.js"></script> -->
<script   src="https://code.jquery.com/jquery-2.2.4.min.js"   integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="   crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
<!-- knockout -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/knockout/3.4.0/knockout-min.js"></script>
</body>
</html>

app/views/partials/_cohorts.html.erb
<h1>Fellow Cohorts and Students</h1>

<table class="table">
  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.cohort %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/partials/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="flash" id="flash">
    <p><strong><%= key %>:</strong> <%= value %></p>
  </div>
<% end %>

app/views/partials/_links.html.erb
<h1>Popular Links</h1>

<h4>Outcomes</h4>
<ul class="list-group">
  <li class="list-group-item"><a href="https://calendly.com/beth-miller">Beth Calendly</a></li>
  <li class="list-group-item"><a href="https://trello-attachments.s3.amazonaws.com/57179c9c2c05a97c4b22e2d2/5746245ff2075d9d622574ac/f9f12a66cc9f0dccbb545581fd451129/What_s_Next-Life_After_GA.pdf">What's Next- Life after GA (PDF)</a></li>
  <li class="list-group-item"><a href="https://trello-attachments.s3.amazonaws.com/57179c9c2c05a97c4b22e2d2/5746245ff2075d9d622574ac/e1ae905c1aef1cfba3ea0dc330614fd4/Resume%2C_Cover_Letter_%26_LinkedIn.pdf">Resume, Cover Letter, LinkedIn (PDF)</a></li>
  <li class="list-group-item"><a href="https://trello-attachments.s3.amazonaws.com/57179c9c2c05a97c4b22e2d2/5746245ff2075d9d622574ac/6355b62c3ee01fb1bd1de07cf9cb8a87/Professional_Brand_%26_Networking.pdf">Professional Brand & Networking (PDF)</a></li>
  <li class="list-group-item"><a href="https://trello-attachments.s3.amazonaws.com/57179c9c2c05a97c4b22e2d2/5746245ff2075d9d622574ac/b42fd4e4cd951299ee3db7818e75fb7a/Job_Search.pdf">Job Search (PDF)</a></li>
</ul>

<h4>Tools</h4>
<ul class="list-group">
  <li class="list-group-item"><a href="https://github.com/">GitHub</a></li>
  <li class="list-group-item"><a href="https://trello.com/">Trello</a></li>
  <li class="list-group-item"><a href="https://slack.com/">Slack</a></li>
  <li class="list-group-item"><a href="https://garnet.wdidc.org/sign_in">Garnet</a></li>
  <li class="list-group-item"><a href="http://www.meetup.com/">Meet Up</a></li>
</ul>

app/views/partials/_meetupSearch.html.erb
<% if @data != nil %> 
  <% @data['results'].each do |d| %>
    <h2><a href="<%= d['event_url'] %>"><%= d['group']['name'] %></a></h1>
    <div class="well">
      <p class="description"><%= sanitize(d['description']) %></p>
    </div>
  <% end %>
<% else %>
  <h3>Found no Search Results for that topic</h3>
<% end %>

app/views/partials/_navBar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">

      <a href="/"><%= image_tag 'gaIcon.jpg' %></a>

      <% if @current_user && @current_user.admin %>
        <%= link_to('Resources', root_path, class: 'btn btn-default navbar-btn') %>
        <%= link_to('Admin', students_path, class: 'btn btn-default navbar-btn') %>
        <%= link_to('Logout', logout_path, method: :delete, class: 'btn btn-default navbar-btn') %>
        <strong><span style="color:white"><%= @current_user.name + ': Administrator' %></span></strong>
      <% elsif @current_user %>
        <%= link_to('Resources', root_path, class: 'btn btn-default navbar-btn') %>
        <%= link_to('Profile', student_path(@current_user.id), class: 'btn btn-default navbar-btn') %>
        <%= link_to('Logout', logout_path, method: :delete, class: 'btn btn-default navbar-btn') %>
        <strong><span style="color:white"><%= @current_user.name + ': Student' %></span></strong>
      <% else %>
        <%= link_to('Login', login_path, class: 'btn btn-default navbar-btn') %>
      <% end %> 
    </div>

       <form action="/" class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="text" class="form-control" name=":topic" placeholder="Search" data-toggle="tooltip" data-placement="bottom" title="Seperate words with commas ','">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      
  </div>
</nav>

app/views/partials/_staffPicks.html.erb
<div class="container">
  <h1>Staff Picks</h1>

<% @picks.each do |p| %>
  <div class="well">
    <h3><a href="<%= p.url %>"><%= p.name %></a></h3>

      <% if (p.host_location != '' && p.host_location != nil) %>
        <label>Host: </label>
        <p class="pick"><%= p.host_location %></p>
      <% end %>

      <% if (p.staff_attending != '' && p.staff_attending != nil) %>
        <label>Staff Attending: </label>
        <p class="pick"><%= p.staff_attending %></p>
        <br>
      <% end %>

      <% if (p.date != '' && p.date != nil) %>
        <label>Date: </label>
        <p class="pick"><%= p.date.to_formatted_s(:long) %></p>
        <br>
      <% end %> 

      <% if p.notes != '' && p.notes != nil %>
        <label>Notes: </label>
        <p><%= p.notes %></p>
      <% end %>
  </div>
<% end %>

</div>