config/routes.rb
Rails.application.routes.draw do

  get 'passwords/new'

  get 'passwords/edit'

  root 'main#index'

  resources :users

  resources :students
  
  resources :reviews

  resources :cohorts

  resources :deliverables

  get 'login', to: 'sessions#new'

  post 'login', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  get 'reset' => 'passwords#new'

  post 'reset' => 'passwords#create'

  get 'reset/:code' => 'passwords#edit', as: :reset_code

  put 'reset/:code' => 'passwords#update'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :student
  has_many :cohorts, through: :student
  has_many :reviews, through: :student
  has_many :deliverables, through: :cohorts

  #attr_accessor :name, :email
  
  accepts_nested_attributes_for :student

  has_secure_password
  
  validates :name,
    presence: true,
    length: {in: 1..30}

  validates :email,
    presence: true,
    email: true,
    uniqueness: {case_sensitive: false}

  validates :password,
    length: {in: 8..72},
    on: :create


  def self.authenticate(params)
    User.find_by_email(params[:email]).try(:authenticate, params[:password])
  end

  def set_password_reset
    self.reset_code = loop do
      code = SecureRandom.urlsafe_base64
      break code unless User.exists?(reset_code: code)
    end
    self.expires_at = 4.hours.from_now
    self.save
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :is_authenticated
  before_action :is_admin, except: [:edit, :update]

  # create a new blank template for user, direct to new user page
  def new
    @user = User.new
  end

  # create a new user in the db, redirect to admin profile
  def create
    user = User.new(user_params)
    if user.save && !user.admin
      user.create_student
      CohortsStudents.create(cohort_id: params[:cohorts_students][:cohort_id], student_id: user.student.id)
      redirect_to students_path
    elsif user.save && user.admin
      redirect_to students_path
    else
      flash[:danger] = user.errors.messages
      redirect_to new_user_path
    end
  end

  # pull user info, populate form, pull up form
  def edit
    @user = User.find_by_id(params[:id])
  end

  # update already existing user
  def update
    User.find(params[:id]).update(user_params)

    person = User.find(params[:id])

    if person.student && @current_user.admin
      check = CohortsStudents.where(student_id: person.student.id).update_all(cohort_id: params[:cohorts_students][:cohort_id])
    end

    redirect_to students_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin, :cohort_ids => [])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_new.html.erb
<div class="container">
  <%= bootstrap_form_for User.new, remote: :true do |f| %>

    <%= f.text_field :name %>
    <%= f.text_field :email %>
    <%= f.password_field :password %>
    <%= f.password_field :password_confirmation %>
    <div class="format-admin">
      <div class="admin-container">
        <div class="student-box">
          <%= f.radio_button :admin, 'false', :checked => true, class: 'student'%>
          <%= f.label :admin_false, 'student' %>
        </div>
        <div class="admin-box">
          <%= f.radio_button :admin, 'true', :checked => false, class: 'admin'%>
          <%= f.label :admin_true, 'admin' %>
        </div>
        <div class="hide_admin">
          <%= collection_select(:cohorts_students, :cohort_id, Cohort.all, :id, :cohort) %>
        </div>
      </div>
    </div>
    <br>
    <%= f.submit %>

  <% end %>
</div>

app/views/users/edit.html.erb
<div class="page-header">
  <h1>Edit User</h1>
</div>

<% if @current_user.admin  || @current_user.id == @user.id %>
  <%= bootstrap_form_for @user do |f| %>
    <br>
    <%= f.text_field :name %>
    <br>
    <%= f.text_field :email %>
    <br>

      <div class="admin-container">
        <% if @current_user.admin %>
          <div class="student-box">
            <%= f.radio_button :admin, 'false', :checked => true, class:'student'%>
            <%= f.label :admin_false, 'student' %>
          </div>
          <div class="admin-box">
            <%= f.radio_button :admin, 'true', :checked => false, class: 'admin'%>
            <%= f.label :admin_true, 'admin' %>
          </div>
      
      <div class="hide_admin">
        <%= collection_select(:cohorts_students, :cohort_id, Cohort.all, :id, :cohort) %>
      </div>
      </div>
    <div class="password">
    <% elsif @current_user.id == @user.id %>
      <%= f.password_field :password %>
      <br>
      <%= f.password_field :password_confirmation %>
    <% end %>
    </div>
    <br>

    <%= f.primary %>

  <% end %>
<% end %>
<hr class="hr">
<div class="reset-password">
  <h2>Reset Password</h2>
  <%= bootstrap_form_tag url: reset_path do |f| %>
    <%= f.email_field :email, placeholder: 'Enter your email', value: @user.email, method: :post%>
    <%= f.submit 'Send Reset Email' %>
  <% end %>
</div>